### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jamley** [kelsin/mysql-mimic#27]
Hi Chris, Chris and Barak

Firstly, thanks for your work on MySQL-mimic!

I'm not the most sophisticated user so took me a while to figure out a few things - could be handy to add to documentation/readme, or to the example script:
- from types import ColumnType (and look at the list of types), from results import ResultColumn, ResultsColumn(name='columnname',type=ColumnType.RELEVANTTYPE)
- need to enforce the datatypes in your resultset - one thing that caught me out with app I am using (Tableau) and the dataset I am trying to serve up (resultset from MySQL server, but returned via query embedded in API call...) was handling "nulls". Shoud use numeric_null = None, string_null = '' (Tableau refused to work until I figured out it didn't like string_null = None)
- will be working through (and might come back with, but in the interim would welcome thoughts on):
- - pretty basic but need to add in MySession query, raise MysqlError("Error text") for errors. not sure whether sqlglot does parsing/identifying invalid queries and raise error off that, or just send to API and return their error message
- - streaming results - haven't tested large resultsets as yet, not sure there's anything special i need to do on the MySQL-mimic side? probably more on the API side
- - i think in the connection/session handle_query need to log a UUID somewhere and remove when query complete - if query is cancelled by client or session closed need to handle cancel behaviour for query/ies

**Comment by barakalon** [comment]
Hi there! And welcome.

> from types import ColumnType (and look at the list of types), from results import ResultColumn, ResultsColumn(name='columnname',type=ColumnType.RELEVANTTYPE)

Yeah, agreed. This deserves some documentation.

> need to enforce the datatypes in your resultset - one thing that caught me out with app I am using (Tableau) and the dataset I am trying to serve up (resultset from MySQL server, but returned via query embedded in API call...) was handling "nulls". Shoud use numeric_null = None, string_null = '' (Tableau refused to work until I figured out it didn't like string_null = None)

Interesting... I think this is a quirk of Tableau.
MySQL supports NULL for string columns, AFAIK.

Might need separate documentation on using mysql-mimic with Tableau...

> pretty basic but need to add in MySession query, raise MysqlError("Error text") for errors. not sure whether sqlglot does parsing/identifying invalid queries and raise error off that, or just send to API and return their error message

Not sure I follow? Are you saying we need to add more documentation about raising errors?

SQLGlot does _some_ validation of queries, but it's not a query validator.

> streaming results - haven't tested large resultsets as yet, not sure there's anything special i need to do on the MySQL-mimic side? probably more on the API side

This _should_ be supported as-is by returning an iterator... but I haven't actually tested it. Happy to work with you on this when you get there.

> i think in the connection/session handle_query need to log a UUID somewhere and remove when query complete - if query is cancelled by client or session closed need to handle cancel behaviour for query/ies

Not sure I follow? 

There are two different lifecycles to consider - connections and queries.

One connection might have many queries.

Query lifetime is encapsulated by the `handle_query`/`query` methods.

You can track when a connection is opened/closed by extending the `Session.init` and `Session.close` methods. The existing implementation saves a reference to the connection, which has a `connection_id` attribute.

There are two main ways for a query to be cancelled:
1. The client just closes the connection
2. The client opens _another_ connection and sends a KILL command with the first connection's ID.

(1) _should_ trigger a CancelledError. But I could've messed that up - let me know.

(2) Is trickier. We currently track all connections on the `MySqlServer` instance. So it should be easy to cancel connections. But this gets trickier depending on your deployment - i.e. if you are horizontally scaling, you might need to broadcast the KILL to all the instances.

Let me know if you have a more specific problem. Happy to work with you on it


---

Thanks for the feedback!

**Comment by barakalon** [comment]
Closing to keep the issue log clean. But feel free to continue the discussion.

**Comment by jamley** [comment]
Thanks! And again apologies - I've been more a (power?) data user/consumer, and whilst I've come a ways since recording VBA macros I'm certainly no software developer. Someone more familiar would probably be better at looking through your code to figure out what needs doing. Also, I've been a little scattered recently - hopefully the below is easier to follow than my first comment.

Once I have things sorted I'll provide a simplified example script - could prove useful for others

Re: string nulls, it could be the way the API I am using returns the resultset (ie header with column names and datatype, but they are system datatypes not MySQL... so nulls here are just where the row is value1,,value3 ie value2 is empty) - Tableau runs some information_schema queries on connecting to a database, and IIRC the tables table had empty comment/description field. When returning value=None for these fields Tableau was unable to proceed further (ie you connect to server, select DB... but it won't list the tables, nor allow for custom sql)

Another apology - some of the items were more a to-do list than an issue list! Case in raising MysqlError("Error text"). Re query validation, I'm sending the query to an actual MySQL server so it does give me some indication of where I've gone wrong but validation potentially a nice-to-have for other use cases.

Yes I am looking at streaming now - it seems like the client/server has some keep-alive signal? Currently I'm not doing async POST request, nor streaming the reponse - if the request takes longer than 30 seconds Workbench throws "Error Code: 2013. Lost connection to MySQL server during query" (I'm guessing didn't receive keep-alive signal so closes connection?), and when the POST request finally finishes, mysql-mimic resumes but "An established connection was aborted by the software in your host machine" (per above client has closed connection?).

What do you mean exactly that I need to return an iterator? Ie my query method returns a tuple(rows,columns) - should the rows variable be a generator that for each reponse.readline() yield a row array? I know we're straying from mysql-mimic here - but also exceeding my limited "expertise"! Getting further away from still from both, but I imagine I'd want to be using aiohttp to make an async POST request as well ().

Thanks for the information re: connection/query methods. Will tackle that down the track.

**Comment by barakalon** [comment]
> Re: string nulls, it could be the way the API I am using returns the resultset (ie header with column names and datatype, but they are system datatypes not MySQL... so nulls here are just where the row is value1,,value3 ie value2 is empty) - Tableau runs some information_schema queries on connecting to a database, and IIRC the tables table had empty comment/description field. When returning value=None for these fields Tableau was unable to proceed further (ie you connect to server, select DB... but it won't list the tables, nor allow for custom sql)

I'd have to see how you're implementing mysql-mimic. You might need to explicitly set the schema/result column.

We use mysql-mimic with Tableau, so I know it's possible.

> Another apology - some of the items were more a to-do list than an issue list! Case in raising MysqlError("Error text"). Re query validation, I'm sending the query to an actual MySQL server so it does give me some indication of where I've gone wrong but validation potentially a nice-to-have for other use cases.

SQLGlot will catch some glaring errors up front. But if you're using MySQL, I'd ultimately leave query validation up to MySQL. 

> Yes I am looking at streaming now - it seems like the client/server has some keep-alive signal? Currently I'm not doing async POST request, nor streaming the reponse - if the request takes longer than 30 seconds Workbench throws "Error Code: 2013. Lost connection to MySQL server during query" (I'm guessing didn't receive keep-alive signal so closes connection?), and when the POST request finally finishes, mysql-mimic resumes but "An established connection was aborted by the software in your host machine" (per above client has closed connection?).

There are two clients:

```mermaid
flowchart LR
    Workbench --> MySQL-Mimic
    MySQL-Mimic --> MySQL
```

You're saying the connection between Workbench and MySQL-Mimic closes after 30 seconds?

MySQL-Mimic doesn't automatically close connections. Does Workbench have a timeout set? You might be able to configure that.
Otherwise, is there some kind of network proxy in between Workbench and MySQL-Mimic?

> What do you mean exactly that I need to return an iterator? Ie my query method returns a tuple(rows,columns) - should the rows variable be a generator that for each reponse.readline() yield a row array? I know we're straying from mysql-mimic here - but also exceeding my limited "expertise"! Getting further away from still from both, but I imagine I'd want to be using aiohttp to make an async POST request as well ().

That's correct - `rows` should be a python Iterator. A generator can be used as an iterator.

We might actually need to make some changes in mysql-mimic to support _async generators_, which you'd probably need. 

Are you sure you would benefit from streaming results? Does Tableau handle streaming results?

**Comment by barakalon** [comment]
> I've also modified the Session class to comment out some of the intercept behaviour (show, information_schema) so that this gets passed through to the API (ie a MySQL database itself).

You can also extend the BaseSession class, which is a little more bare bones.
