### ISSUE TITLE
HOW-TO: Distinguish between fetchall/fetchmany on mimic server?

### ISSUE THREAD

**Issue by pandalanax** [kelsin/mysql-mimic#43]
Hello all,
first thank you for this repo, it has a big potential to solve several issues in our usecase to proxy requests to our bigdata cluster.

## Questions
We wondered if there is a possibility to distinguish between the clients called methods.
i.e. when the client uses the cursor to fetch the rows via `cursor.fetchall()`, is it possible to somehow see that the client wants all data compared to `cursor.fetchmany()`

## Why
There is a need for distinction as the data can get really big so clients should be able to use `cursor.fetchmany()` to sequentially request data and process it. Same goes for the proxy as RAM is limited.

## Background
We have a [https://drill.apache.org/](https://drill.apache.org/) cluster and want to restrict direct access via odbc/REST/etc... 
So we developed a drill-proxy which looks like the following:
```
Client <-------------> Proxy <-------------> Server
            HTTP                   ODBC
```
It occurred to us that essentially what we are doing is mimicking a database which one can access via HTTP. We want to use a transimission which also uses pythons [https://peps.python.org/pep-0249/](https://peps.python.org/pep-0249/) on the client (in this case mysql.connector). mysql-mimic seems perfect for that.

**Comment by barakalon** [comment]
hi @pandalanax -

`fetchall` and `fetchmany` are PEP-249 DBAPI methods - they are not part of the MySQL protocol. So its not possible to distinguish between them.

That being said, I believe what need to do is **return an iterator**.

Here is a toy example:

```python
from mysql_mimic import ResultColumn
from mysql_mimic.types import ColumnType

class MySession(Session):
    async def query(self, expression, sql, attrs):
        # Construct the mysql_mimic ResultColumn manually, instead of letting it get inferred
        # because mysql_mimic doesn't know how to infer types from iterators yet.
        columns = [ResultColumn("col1", ColumnType.LONGLONG)]

        # range iterates over values and doesn't hold them all in memory
        rows = range(1000000)

        return rows, columns
```

That being said, I think you need an _async_ iterator, so you can also stream from drill. Let me add support for that today.

**Comment by barakalon** [comment]
Async iterators are now supported in v2.4.0

An example: https://github.com/kelsin/mysql-mimic/blob/main/examples/streaming_results.py

Let me know if you have more questions.

**Comment by pandalanax** [comment]
Hi barakalon!
Wow, thank you so much for the quick response! We were able to work it out and will do a PR with a `db_api_proxy_streaming.py` example in the coming days. 
Now that this works, we decided to deploy mysql-mimic in our setup and develop the proxy further. Hopefully, on the way, we will be able to contribute to this repo!

**Comment by barakalon** [comment]
Sweet - glad it’s working 👍
